languageCode = "en-AU"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Home"
copyright = "&copy; 2025 Yuanyuan Zhou"

[params]
  dateFormat = "25 January 2025"
  mainSections = ["Projects"]

[params.author]
  name = "Yuanyuan Zhou"
  image = "img/selfie.jpg"
  headline = "PhD Student in Security & Privacy"
  bio = "I'm a first-year PhD student in Electronic and Electrical Engineering (EEE) at University College London (UCL), supervised by [Dr.Anna Maria Mandalari](https://profiles.ucl.ac.uk/89052). I have a solid background in Machine Learning and Telecommunication. I am currently investigating Honeypots and IPv6 in the context of IoT security and privacy."
  links = [
    { github = "https://github.com/CIRCIRCIRCLE/" },
    { email = "mailto:yuanyuan.zhou.23@ucl.ac.uk" },
    { linkedin = "https://www.linkedin.com/in/yuanyuan-zhou-b71258282/" },
    { file = "https://drive.google.com/file/d/1AkzuDcZ6MDThtRqHXH7A93V6bR7gT5qC/view?usp=drive_link"},
  ]