languageCode = "zh-CN"
languageName = "简体中文"
languageDirection = "ltr"
weight = 1

title = "主页"
copyright = "&copy; 2024 Congo contributors"

[params]
  dateFormat = "2025年1月25日"

  mainSections = ["Projects"]

[params.author]
  name = "周园圆"
  image = "img/selfie.jpg"
  headline = "PhD学生 安全与隐私"
  bio = "我当前在伦敦大学学院（UCL）攻读EEE博士学位，主要研究IoT, 安全与隐私，计算机网络的相关技术。"
  links = [
    { github = "https://github.com/CIRCIRCIRCLE/" },
    { email = "mailto:zyywlpre@gmail.com" },
    { linkedin = "https://www.linkedin.com/in/yuanyuan-zhou-b71258282/" },
    { file = "https://drive.google.com/file/d/1LaQ9PdphtfzSsjdALqNb7ifbMkkgqXxV/view?usp=drive_link"},
  ]
